name: CI/CD

on:
  push:
    branches: [main,next]
  pull_request:
    branches: [main]
  # This is to catch new releases of VS Code which could cause the extension to break
  schedule:
    - cron: 0 0 * * *

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        vscode-version: [stable]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.6.0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: lts/*

      - run: npm ci

      - name: Test with VS Code ${{ matrix.vscode-version }}
        uses: coactions/setup-xvfb@v1
        env:
          VSCODE_TEST_VERSION: ${{ matrix.vscode-version }}
        with:
          run: npm test
          options: "-screen 0 1600x1200x24"

  build:
    outputs:
      is_new: ${{ steps.semver_check.outputs.new_release_published }}
      channel: ${{ steps.semver_check.outputs.new_release_channel }}
      semver: ${{ steps.semver_check.outputs.new_release_version }}
      shortver: ${{ steps.shortversion.outputs.semver }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: universal
    
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0

      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: lts/*

      - if: matrix.target != 'universal'
        name: Install dependencies (with binaries)
        run: npm ci
        env:
          npm_config_arch: ${{ matrix.npm_config_arch }}

      - if: matrix.target == 'universal'
        name: Install dependencies (without binaries)
        run: npm ci

      - name: Action For Semantic Release
        id: semver_check
        uses: cycjimmy/semantic-release-action@v3.2.0
        with:
          dry_run: true
        env:
          GH_TOKEEN: ${{ secrets.SEMVER_TOKEN }}

      - name: crate changelog
        run: |
          cat >CHANGELOG.md <<EOF
          ${{ steps.semver_check.outputs.new_release_changelog }}
          EOF

      - name: set short version of (${{ needs.build.outputs.semver }})
        id: shortversion
        run: echo "semver=${{ steps.semver_check.outputs.new_release_major }}.${{ steps.semver_check.outputs.new_release_minor }}.${{ steps.semver_check.outputs.new_release_patch }}" >$GITHUB_OUTPUT
    
      - name: Build Package (non prod)
        run: vsce package --pre-release --no-git-tag-version --target=${{ matrix.platform }} ${{ steps.shortversion.outputs.semver }}
        env:
          NODE_ENV: development
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'

      - name: Build Package (prod)
        run: vsce package --no-git-tag-version  --target=${{ matrix.platform }} ${{ steps.shortversion.outputs.semver}}
        env:
          NODE_ENV: production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: "*.vsix"

  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: universal

    needs: [build, test]
    if: needs.build.outputs.is_new == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0

      - name: Setup Node version
        uses: actions/setup-node@v3.6.0
        with:
          node-version: lts/*

      - run: actions/download-artifact@v3

      - name: Publish to Visual Studio Marketplace (Edge)
        run: vsce publish --packagePath "./writer-name-handler-${{ needs.build.outputs.shortver }}.vsix" --pre-release --no-git-tag-version 
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to Visual Studio Marketplace (Stable)
        run: vsce publish --packagePath "./writer-name-handler-${{ needs.build.outputs.shortver }}" --no-git-tag-version --no-update-package-json 
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX Registry (Edge)
        uses: HaaLeo/publish-vscode-extension@v1
        if: false && github.event_name != 'push' || github.ref != 'refs/heads/main'
        with:
          preRelease: true
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ./marquee-${{ env.RELEASE_VERSION }}.vsix

      - name: Publish to Open VSX Registry (Stable)
        uses: HaaLeo/publish-vscode-extension@v1
        if: false && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          preRelease: false
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ./marquee-${{ env.RELEASE_VERSION }}.vsix

      - name: Action For Semantic Release
        id: semver_check
        uses: cycjimmy/semantic-release-action@v3.2.0
        env:
          GH_TOKEEN: ${{ secrets.SEMVER_TOKEN }}
