name: 'Dependabot Batcher: Scheduled'
on:
  workflow_dispatch

jobs:
  # Batches Dependabot PRs into one by merging them into a combined branch, then raising a new PR
  dependabot-batcher:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot Batcher
        uses: Legal-and-General/dependabot-batcher@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          baseBranchName: 'beta' #optional
          batchBranchName: 'dep-batcher-updates' #optional
          batchPullTitle: 'Dependabot Batcher Updates' #optional
